### ISSUE TITLE
CameraPreviewScanner different results iOS

### ISSUE THREAD

**Issue by thegenet** [brianmtully/flutter_google_ml_vision#5] opened 2021-04-29 21:51 UTC
First thanks for your work to implement the standalone ML Kit because the firebase_ml_vision is not working with Flutter 2. I having different results with the example CameraPreviewScanner and PictureScanner. I try changing the ResolutionPreset.high and ResolutionPreset.veryHigh but still the same results.

Results from android 10, device Xiaomi mi 9T :
![Screen Shot 2021-04-29 at 16 36 11](https://user-images.githubusercontent.com/46535999/116622698-ba949980-a90a-11eb-9c43-393bb5c864a9.png)

Result from iOS, device iPhone x with iOS 14:

![Screen Shot 2021-04-29 at 16 28 05](https://user-images.githubusercontent.com/46535999/116622862-f92a5400-a90a-11eb-8f96-165bd93b878a.png)

**Comment by nirbar89** [comment] 2021-04-30 05:57
Hey @thegenet 

let me understand, you use the same frame and get different results on different devices?

**Comment by thegenet** [comment] 2021-04-30 13:55
Thats right, is the same frame that I'm using, it is a UPS package label

**Comment by nirbar89** [comment] 2021-04-30 19:03
I think the issue is in the ML-Kit SDK and we don’t have nothing to do with that at this moment.

To confirm Try this: change to firebase_ml_vision 
Do on device image labelling and see the results.

@brianmtully you can close this: not a library bug.

**Closed as completed** 2021-04-30 19:10 UTC
